services:
  - type: web
    name: automatic
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --workers=1 --threads=4 --timeout=120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: MultExchange
      - key: ENCRYPTION_KEY
        sync: false
